language: cpp

env:
  - EIGEN_VERSION=3.1.0 EIGEN_HASH=ca142d0540d3 MSGPACK_C_VERSION="1.4.2"

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -yqq
  - sudo apt-get install -yqq software-properties-common python-software-properties
  - sudo add-apt-repository -y ppa:chris-lea/zeromq
  - sudo add-apt-repository -y ppa:tuleu/precise-backports
  - sudo add-apt-repository -y ppa:andykimpe/cmake
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -yqq
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -yqq g++-4.8; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++
    /usr/bin/g++-4.8 50; fi

install:
  - sudo apt-get update -yqq
  - sudo apt-get install -yqq
    cmake
    wget
    libboost1.54-dev
    libboost-regex1.54-dev
    libboost-filesystem1.54-dev
    libboost-system1.54-dev
    libboost-test1.54-dev
    libzmq3-dev
    libgflags-dev
    libgoogle-glog-dev
    mpich2
    ruby automake libtool
  - cd /tmp
  - wget -O "/tmp/msgpack-c-${MSGPACK_C_VERSION}.tar.gz"
    "https://github.com/msgpack/msgpack-c/archive/cpp-${MSGPACK_C_VERSION}.tar.gz"
  - tar -zxvf "/tmp/msgpack-c-${MSGPACK_C_VERSION}.tar.gz" "msgpack-c-cpp-${MSGPACK_C_VERSION}"
  - cd "/tmp/msgpack-c-cpp-${MSGPACK_C_VERSION}"
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - cd /tmp && rm -rf /tmp/msgpack-c*
  - wget -O "$EIGEN_VERSION.tar.gz" "http://bitbucket.org/eigen/eigen/get/${EIGEN_VERSION}.tar.gz"
  - tar -zxvf "$EIGEN_VERSION.tar.gz" "eigen-eigen-${EIGEN_HASH}"
  - mkdir -p "/tmp/eigen-eigen-${EIGEN_HASH}/build"
  - cd "/tmp/eigen-eigen-${EIGEN_HASH}/build"
  - cmake ..
  - make
  - sudo make install
  - cd /tmp && rm -rf /tmp/eigen*

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - sudo mkdir -p "/opt/paracel"
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/opt/paracel ..

after_failure:
  - "cat /home/travis/build/xunzhang/paracel-1/build/CMakeFiles/CMakeError.log"
  - "cat /home/travis/build/douban/paracel/build/CMakeFiles/CMakeError.log"

script:
  - make -j$(nproc)
  - make test
  - sudo make install
  - cd /tmp
  - wget "paracel.io/data/kjv12.txt" -O "data.txt"
  - wget "paracel.io/data/travis_demo.json"
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/paracel/lib
  - /opt/paracel/prun.py -p 2 -w 2 -c travis_demo.json -m local /opt/paracel/bin/wc

branches:
  except:
    - legacy
